#!/bin/sh

# Sample LINE (latter from newer version)
# C1.19,085,116,068,0000,0
# C123b,085,116,068,0000,0
# V2
# +1.10,118,128,092,0000,0,0
#
# LINE parts (separated by ,) parsed as:
#   - +1.10 - Firmware version number
#   - 085   - real/actual steam temperature in Celsius
#   - 116   - target steam temperature in Celsius
#   - 068   - real/actual heat exchanger temperature in Celsius
#   - 0000  - countdown used to track if the machine is in "fast heating" mode, it seems to go anywhere from 1500-0. 0 means it's no longer boosting
#   - 0     - heating element on/off, 0 is off, 1 is on
#   - 0     - Pump on or off. 1 is on 0 is off
COUNTER=0
while read -r LINE; do
  if echo "$LINE" | grep -Eq "[^,]+,\d{3},\d{3},\d{3},\d{4},\d{1},\d{1}"; then
    COUNTER_CHECK=$(echo "$LINE" | tr -d '\r' | cut -d',' -f7)
    if [ "$COUNTER_CHECK" -eq 1 ]; then
      COUNTER=$((COUNTER + 1))
    else
      COUNTER=0
    fi
    echo "$(date +%s),$LINE,$COUNTER"
  else
    echo "Regex failed for line [$LINE]" >&2
  fi
done
